from __future__ import annotations

from typing import Any


SCENARIO_PROFILES: dict[str, dict[str, Any]] = {
    "case_review_ready": {
        "project_base": {
            "project_name": "Review Ready Project",
            "project_type_raw": "building",
            "engineering_domain": "building_construction",
            "bid_control_price": 18000000,
            "bid_eval_method": "comprehensive",
            "public_chain_status": "COMPLETE",
            "opening_record_count": 1,
            "invalid_bid_count": 0,
        },
        "stage4": {
            "evidence_id": "evidence-review-001",
            "source_url": "https://ggzy.example.cn/review/result",
            "capture_type": "html_snapshot",
            "capture_time": "2026-04-04T17:20:00+08:00",
            "page_title": "Review ready notice",
            "snippet": "Public result notice confirms a competitor clue that still needs manual review.",
            "evidence_artifact_refs": ["artifact://review/result-notice.html"],
            "structured_field_refs": ["field://project-cn-review-001/public_chain_status"],
            "evidence_grade": "B",
            "rule_hit_id": "rule-hit-review-001",
            "rule_code": "REAL_COMPETITOR_IDENTIFIED",
            "severity": "MEDIUM",
            "confidence": 0.82,
            "result_type": "CLUE",
            "why_hit": "A competitor cluster was detected from public tender results.",
            "boundary_note": "Public evidence is traceable but still requires manual review before promotion to OPEN.",
            "target_entity_type": "bidder",
            "target_entity_id": "bidder-review-001",
            "review_status": "PENDING",
            "request_id": "review-request-review-001",
            "request_type": "MANUAL_COMPETITOR_CONFIRMATION",
            "reason": "A medium-risk competitor clue must be confirmed before the project can move to OPEN.",
            "public_basis": "Public result notice is complete but the competitor signal still needs analyst confirmation.",
            "requested_materials": ["public result notice", "opening record excerpt"],
            "priority": "MEDIUM",
        },
        "stage5": {
            "report_id": "report-review-001",
            "brief_path": "reports/review-ready/brief.md",
            "evidence_pack_path": "reports/review-ready/evidence-pack.zip",
            "objection_draft_path": "reports/review-ready/objection-draft.md",
            "review_request_list_path": "reports/review-ready/review-requests.json",
            "review_task_status": "PENDING_REVIEW",
            "report_status": "READY",
            "written_back_at": "2026-04-04T18:10:00+08:00",
        },
        "stage6": {
            "fact_version": 1,
            "fact_refresh_trigger": "RULE_PIPELINE_REFRESH",
            "fact_source_summary": "Derived from review-ready project_base, rule_hit, and report_record.",
            "rule_hit_summary": "One medium-risk clue remains open.",
            "clue_summary": "Competitor clue is still pending manual confirmation.",
            "sale_gate_status": "REVIEW",
            "real_competitor_count": 3,
            "serviceable_competitor_count": 2,
            "competitor_quality_grade": "B",
            "price_cluster_score": 68,
            "price_gradient_pattern": "NARROW_BAND",
            "fact_summary": "Project is sellable after review of the remaining competitor clue.",
            "risk_summary": "Manual review is still required before promotion to OPEN.",
            "manual_override_status": "PENDING",
            "last_fact_refreshed_at": "2026-04-04T18:00:00+08:00",
        },
    },
    "case_open_issued": {
        "project_base": {
            "project_name": "Open Issued Project",
            "project_type_raw": "municipal",
            "engineering_domain": "municipal_engineering",
            "bid_control_price": 26000000,
            "bid_eval_method": "lowest_price",
            "public_chain_status": "COMPLETE",
            "opening_record_count": 1,
            "invalid_bid_count": 0,
        },
        "stage4": {
            "evidence_id": "evidence-open-001",
            "source_url": "https://ggzy.example.cn/open/result",
            "capture_type": "html_snapshot",
            "capture_time": "2026-04-04T17:30:00+08:00",
            "page_title": "Open issued notice",
            "snippet": "Public result notice confirms a clean, fully traceable public chain.",
            "evidence_artifact_refs": ["artifact://open/result-notice.html"],
            "structured_field_refs": ["field://project-cn-open-001/public_chain_status"],
            "evidence_grade": "A",
            "rule_hit_id": "rule-hit-open-001",
            "rule_code": "PUBLIC_CHAIN_CONFIRMED",
            "severity": "LOW",
            "confidence": 0.96,
            "result_type": "AUTO_HIT",
            "why_hit": "Public chain and competition evidence are complete and consistent.",
            "boundary_note": "All public evidence has been confirmed and no unresolved clue remains.",
            "target_entity_type": "project",
            "target_entity_id": "project-cn-open-001",
            "review_status": "CONFIRMED",
            "request_id": "review-request-open-001",
            "request_type": "CLOSEOUT_CONFIRMATION",
            "reason": "Final closeout confirmation is recorded even though no blocking clue remains.",
            "public_basis": "Public result notice and report evidence are already confirmed.",
            "requested_materials": ["final report brief"],
            "priority": "LOW",
        },
        "stage5": {
            "report_id": "report-open-001",
            "brief_path": "reports/open-issued/brief.md",
            "evidence_pack_path": "reports/open-issued/evidence-pack.zip",
            "objection_draft_path": "reports/open-issued/objection-draft.md",
            "review_request_list_path": "reports/open-issued/review-requests.json",
            "review_task_status": "COMPLETED",
            "report_status": "ISSUED",
            "written_back_at": "2026-04-04T18:20:00+08:00",
        },
        "stage6": {
            "fact_version": 2,
            "fact_refresh_trigger": "REPORT_WRITEBACK",
            "fact_source_summary": "Derived from open-issued project_base, rule_hit, and issued report_record.",
            "rule_hit_summary": "Public chain confirmation has been fully confirmed.",
            "clue_summary": "No unresolved clue remains.",
            "sale_gate_status": "OPEN",
            "real_competitor_count": 1,
            "serviceable_competitor_count": 1,
            "competitor_quality_grade": "A",
            "price_cluster_score": 82,
            "price_gradient_pattern": "STABLE_SPREAD",
            "fact_summary": "Project is open for standard downstream sales and delivery consumption.",
            "risk_summary": "No blocking or hold condition remains after confirmation.",
            "manual_override_status": "NONE",
            "last_fact_refreshed_at": "2026-04-04T18:20:00+08:00",
        },
    },
    "case_hold_incomplete_chain": {
        "project_base": {
            "project_name": "Hold Incomplete Chain Project",
            "project_type_raw": "highway",
            "engineering_domain": "transportation",
            "bid_control_price": 32000000,
            "bid_eval_method": "comprehensive",
            "public_chain_status": "INCOMPLETE",
            "opening_record_count": 0,
            "invalid_bid_count": 0,
        },
        "stage4": {
            "evidence_id": "evidence-hold-001",
            "source_url": "https://ggzy.example.cn/hold/public-chain",
            "capture_type": "html_snapshot",
            "capture_time": "2026-04-04T17:40:00+08:00",
            "page_title": "Incomplete chain notice",
            "snippet": "Public chain notice shows that an opening record is still unavailable.",
            "evidence_artifact_refs": ["artifact://hold/public-chain.html"],
            "structured_field_refs": ["field://project-cn-hold-001/public_chain_status"],
            "evidence_grade": "B",
            "rule_hit_id": "rule-hit-hold-001",
            "rule_code": "PUBLIC_CHAIN_INCOMPLETE",
            "severity": "HIGH",
            "confidence": 0.88,
            "result_type": "CLUE",
            "why_hit": "The public chain is incomplete and opening records are missing.",
            "boundary_note": "The project cannot move to OPEN until the public chain is complete.",
            "target_entity_type": "project",
            "target_entity_id": "project-cn-hold-001",
            "review_status": "PENDING",
            "request_id": "review-request-hold-001",
            "request_type": "PUBLIC_CHAIN_COMPLETION",
            "reason": "The public chain is incomplete and must be completed before the project can proceed.",
            "public_basis": "The latest public chain notice shows that required public records are missing.",
            "requested_materials": ["opening record", "result publication notice"],
            "priority": "HIGH",
        },
        "stage5": {
            "report_id": "report-hold-001",
            "brief_path": "reports/hold-incomplete/brief.md",
            "evidence_pack_path": "reports/hold-incomplete/evidence-pack.zip",
            "objection_draft_path": "reports/hold-incomplete/objection-draft.md",
            "review_request_list_path": "reports/hold-incomplete/review-requests.json",
            "review_task_status": "WAITING_CHAIN_COMPLETION",
            "report_status": "DRAFT",
            "written_back_at": "2026-04-04T18:30:00+08:00",
        },
        "stage6": {
            "fact_version": 3,
            "fact_refresh_trigger": "PUBLIC_CHAIN_REFRESH",
            "fact_source_summary": "Derived from incomplete-chain project_base, rule_hit, and draft report_record.",
            "rule_hit_summary": "Public chain completeness is still unresolved.",
            "clue_summary": "The project remains on hold until public records are complete.",
            "sale_gate_status": "HOLD",
            "real_competitor_count": 0,
            "serviceable_competitor_count": 0,
            "competitor_quality_grade": "C",
            "price_cluster_score": 41,
            "price_gradient_pattern": "UNCERTAIN",
            "fact_summary": "Project cannot progress while the public chain remains incomplete.",
            "risk_summary": "Incomplete public chain keeps the project on HOLD.",
            "manual_override_status": "PENDING",
            "last_fact_refreshed_at": "2026-04-04T18:30:00+08:00",
        },
    },
    "case_block_high_risk": {
        "project_base": {
            "project_name": "Block High Risk Project",
            "project_type_raw": "building",
            "engineering_domain": "building_construction",
            "bid_control_price": 41000000,
            "bid_eval_method": "comprehensive",
            "public_chain_status": "COMPLETE",
            "opening_record_count": 1,
            "invalid_bid_count": 2,
        },
        "stage4": {
            "evidence_id": "evidence-block-001",
            "source_url": "https://ggzy.example.cn/block/result",
            "capture_type": "pdf_snapshot",
            "capture_time": "2026-04-04T17:50:00+08:00",
            "page_title": "High-risk result notice",
            "snippet": "Public result notice and pricing pattern indicate a high-risk collusion signal.",
            "evidence_artifact_refs": ["artifact://block/result-notice.pdf"],
            "structured_field_refs": ["field://project-cn-block-001/invalid_bid_count"],
            "evidence_grade": "A",
            "rule_hit_id": "rule-hit-block-001",
            "rule_code": "BID_COLLUSION_HIGH_RISK",
            "severity": "HIGH",
            "confidence": 0.97,
            "result_type": "AUTO_HIT",
            "why_hit": "Public tender results and evidence indicate a high-risk collusion pattern.",
            "boundary_note": "The project must remain BLOCK until the high-risk hit is resolved or overturned.",
            "target_entity_type": "bidder",
            "target_entity_id": "bidder-block-001",
            "review_status": "CONFIRMED",
            "request_id": "review-request-block-001",
            "request_type": "LEGAL_REVIEW",
            "reason": "A high-risk public hit requires formal legal and analyst review before any release.",
            "public_basis": "Public result notice and evidence excerpt indicate a high-risk collusion pattern.",
            "requested_materials": ["full evidence pack", "pricing review memo"],
            "priority": "HIGH",
        },
        "stage5": {
            "report_id": "report-block-001",
            "brief_path": "reports/block-high-risk/brief.md",
            "evidence_pack_path": "reports/block-high-risk/evidence-pack.zip",
            "objection_draft_path": "reports/block-high-risk/objection-draft.md",
            "review_request_list_path": "reports/block-high-risk/review-requests.json",
            "review_task_status": "LEGAL_REVIEW_PENDING",
            "report_status": "DRAFT",
            "written_back_at": "2026-04-04T18:40:00+08:00",
        },
        "stage6": {
            "fact_version": 4,
            "fact_refresh_trigger": "HIGH_RISK_RULE_HIT",
            "fact_source_summary": "Derived from high-risk project_base, rule_hit, and draft report_record.",
            "rule_hit_summary": "A high-risk auto-hit blocks the project.",
            "clue_summary": "No soft clue path remains; the project is in a blocking state.",
            "sale_gate_status": "BLOCK",
            "real_competitor_count": 5,
            "serviceable_competitor_count": 0,
            "competitor_quality_grade": "D",
            "price_cluster_score": 14,
            "price_gradient_pattern": "COLLUSION_PATTERN",
            "fact_summary": "Project is blocked by a confirmed high-risk public hit.",
            "risk_summary": "A confirmed high-risk hit blocks sales and delivery until explicit resolution.",
            "manual_override_status": "BLOCK_CONFIRMED",
            "last_fact_refreshed_at": "2026-04-04T18:40:00+08:00",
        },
    },
}


def get_scenario_profile(scenario_id: str) -> dict[str, Any]:
    try:
        return SCENARIO_PROFILES[scenario_id]
    except KeyError as error:
        raise ValueError(f"unsupported scenario_id: {scenario_id}") from error


def get_scenario_id(raw_payload: dict[str, Any]) -> str:
    scenario_id = raw_payload.get("scenario_id")
    if not isinstance(scenario_id, str) or not scenario_id:
        raise ValueError("raw payload must include scenario_id")
    get_scenario_profile(scenario_id)
    return scenario_id
